### ISSUE TITLE
How to flash?

### ISSUE THREAD

**Issue by grahamcropley** [tbs-fpv/freedomtx#7]
I have forked and compiled, can anybody explain how to flash my build to the Tango2? I want to test before trying to contribute back.

Also, is there a FB Group / Slack / Discord I could join?

**Comment by alexvanh** [comment]
I asked TBS support about this, the reply was: "this is not possible at this time, it will be added when freedomtx merges back with opentx."

I think the Tango 2 is running a custom TBS bootloader rather than the regular OpenTX bootloader, so the normal ways of updating OpenTX won't work. I couldn't find a way to put the STM32 in DFU mode either.

I've been trying to find a way. I think it might be possible to flash using an stlink, but you will need to generate a firmware.bin with the TBS bootloader and the modified firmware, or only flash the firmware area of flash with the firmware portion of firmware.bin and leave the bootloader area alone.

**Comment by tobiasbischoff** [comment]
Thats kind of sad. Its technically not a real open source product when you cant compile and flash yourself.

**Comment by grahamcropley** [comment]
@tobiasbischoff I get your point, but FreedomTX is a fork that TBS have created specifically to add support for this new hardware, I don't believe it's the intention that FreedomTX will live beyond OpenTX 2.4 when these additions are merged back.

@alexvanh I guess they have to run their own bootloader because there's only 1 USB port that now has to have access to flash Crossfire TX module, OpenTX/FreedomTX OS, and be used for SD Mass Storage + Joystick HID + Agent X connectivity. I'd imaging the additional work to open that up to custom build / custom flash process outside of Agent X is more effort than the outstanding bug fixes which they seem to be on top of until it's merged back with OpenTX.

I understand the technical aspects a bit more now, so I will close this. Thanks both for replying!
